import { createSlice } from '@reduxjs/toolkit';

// Define the initial state for the user slice
const initialState = {
  users: [],
  loading: false,
  error: null,
};

// Create a user slice
const userSlice = createSlice({
  name: 'user',
  initialState,
  reducers: {
    // Reducer to update state when user data is being loaded
    fetchUsersStart(state) {
      state.loading = true;
      state.error = null;
    },
    // Reducer to update state when user data has been successfully loaded
    fetchUsersSuccess(state, action) {
      state.loading = false;
      state.users = action.payload;
    },
    // Reducer to update state when user data loading fails
    fetchUsersFailure(state, action) {
      state.loading = false;
      state.error = action.payload;
    },
  },
});

// Export actions generated by the user slice
export const { fetchUsersStart, fetchUsersSuccess, fetchUsersFailure } = userSlice.actions;

// Export the user reducer
export default userSlice.reducer;
